################################
# Istio ingress controller
################################
apiVersion: v1
kind: Service
metadata:
  name: istio-ingress-controller
  labels:
    infra: istio-ingress-controller
spec:
  type: LoadBalancer
  ports:
  - port: 80
#   nodePort: 32000
    name: http
  selector:
    infra: istio-ingress-controller
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-ingress-controller
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.istio.io/sidecar: ignore
      labels:
        infra: istio-ingress-controller
    spec:
      containers:
      - name: istio-ingress-controller
        image: docker.io/istio/runtime:2017-03-22-21.21.48
        args:
        - proxy
        - ingress
        - -v
        - "2"
        - -n
        - $(POD_NAMESPACE)
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
