############################################################
# Pod with the hello frontend from Kubernetes documentation
# and an Istio proxy
############################################################
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: hello
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: backend
        track: stable
      annotations:
        # init container uses iptables rules to redirect traffic to the proxy
        pod.beta.kubernetes.io/init-containers: >
          [{
            "name": "iptables",
            "image": "docker.io/istio/runtime:2017-03-17-22.11.25",
            "imagePullPolicy": "Always",
            "securityContext": { "capabilities" : { "add" : ["NET_ADMIN"] } }
          }]
    spec:
      containers:
      - name: app
        image: gcr.io/google-samples/hello-go-gke:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      - name: proxy
        image: docker.io/istio/runtime:2017-03-17-22.11.25
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1337
        args:
            - proxy
            - sidecar
            - -n
            - default
            - -s
            - istio-manager:8080
            - -v
            - "2"
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
---
