apiVersion: istio.io/v1alpha1
kind: IstioConfig
metadata:
  name: route-rule-productpage-v1
  namespace: default
spec:
  destination: productpage.default.svc.cluster.local
  precedence: 1
  route:
  - tags:
      version: v1
    weight: 100
---
apiVersion: istio.io/v1alpha1
kind: IstioConfig
metadata:
  name: route-rule-reviews-v1
  namespace: default
spec:
  destination: reviews.default.svc.cluster.local
  precedence: 1
  route:
  - tags:
      version: v1
    weight: 100
---
apiVersion: istio.io/v1alpha1
kind: IstioConfig
metadata:
  name: route-rule-ratings-v1
  namespace: default
spec:
  destination: ratings.default.svc.cluster.local
  precedence: 1
  route:
  - tags:
      version: v1
    weight: 100
---
apiVersion: istio.io/v1alpha1
kind: IstioConfig
metadata:
  name: route-rule-details-v1
  namespace: default
spec:
  destination: details.default.svc.cluster.local
  precedence: 1
  route:
  - tags:
      version: v1
    weight: 100
