# This CA issues certs/keys for the entire cluster.
# Please make sure only one CA is deployed per cluster.
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: istio-ca
spec:
  replicas: 1
  template:
    metadata:
      labels:
        istio: istio-ca
    spec:
      containers:
      - name: istio-ca
        image: docker.io/istio/istio-ca:2017-04-13-17.43.08
        imagePullPolicy: IfNotPresent
